-- Schema Definition: Gym Member Exercise Tracking Database
-- Creates four tables in a star-schema-like design with WORKOUT_SESSION as the fact table.
-- MySQL syntax (AUTO_INCREMENT for surrogate keys).

-- Create GYM_MEMBER (dimension)
CREATE TABLE GYM_MEMBER
(Member_ID INT AUTO_INCREMENT,
 Age INT NOT NULL,
 Gender VARCHAR(10) NOT NULL,
 Weight DECIMAL(5, 2) NOT NULL,
 Height DECIMAL(5, 2) NOT NULL,
 Fat_Percent DECIMAL(5, 2) NOT NULL,
 Water_Intake DECIMAL(5, 2) NOT NULL,
 Experience_Level INT NOT NULL DEFAULT 0,
 CONSTRAINT PK_GYM_MEMBER PRIMARY KEY (Member_ID));

-- Create WORKOUT_TYPE (dimension)
CREATE TABLE WORKOUT_TYPE
(Type_ID INT AUTO_INCREMENT,
 Workout_Type VARCHAR(10) NOT NULL,
 CONSTRAINT PK_WORKOUT_TYPE PRIMARY KEY (Type_ID));

-- Create WORKOUT_SESSION (fact table)
CREATE TABLE WORKOUT_SESSION
(Session_ID INT AUTO_INCREMENT,
 Member_ID INT NOT NULL,
 Type_ID INT NOT NULL,
 Session_Duration DECIMAL(5, 2) NOT NULL,
 Calories_Burned INT NOT NULL,
 Workout_Frequency INT NOT NULL DEFAULT 3,
 CONSTRAINT PK_WORKOUT_SESSION PRIMARY KEY (Session_ID),
 CONSTRAINT FK_GYM_MEMBER FOREIGN KEY (Member_ID) REFERENCES GYM_MEMBER(Member_ID),
 CONSTRAINT FK_WORKOUT_TYPE FOREIGN KEY (Type_ID) REFERENCES WORKOUT_TYPE(Type_ID));

-- Create HEART_RATE (dimension)
CREATE TABLE HEART_RATE
(Heart_Rate_ID INT AUTO_INCREMENT,
 Session_ID INT NOT NULL,
 Max_Bpm INT NOT NULL,
 Avg_Bpm INT NOT NULL,
 Resting_Bpm INT NOT NULL DEFAULT 60,
 CONSTRAINT PK_HEART_RATE PRIMARY KEY (Heart_Rate_ID),
 CONSTRAINT FK_WORKOUT_SESSION FOREIGN KEY (Session_ID) REFERENCES WORKOUT_SESSION(Session_ID));
